// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day10_Tests.Test_AsteroidMap_BestPositionFound(System.Collections.Generic.List{System.String},System.Int32,AoC.Common.Mapping.Position)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day10_Tests.Test_AsteroidMap_MaxAsteroidsDetected(System.Collections.Generic.List{System.String},System.Int32,AoC.Common.Mapping.Position)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "xUnit1026:Theory methods should use all of their parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day10_Tests.Test_AsteroidMap_BestPositionFound(System.Collections.Generic.List{System.String},System.Int32,AoC.Common.Mapping.Position)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "xUnit1026:Theory methods should use all of their parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day10_Tests.Test_AsteroidMap_MaxAsteroidsDetected(System.Collections.Generic.List{System.String},System.Int32,AoC.Common.Mapping.Position)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "xUnit1026:Theory methods should use all of their parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day14_Tests.Test_NanoReactor_Fuel_Produced_By_1_Trillion_Ore(System.Collections.Generic.List{System.String},System.Int64,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "xUnit1026:Theory methods should use all of their parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day14_Tests.Test_NanoReactor_Produce_1_Fuel(System.Collections.Generic.List{System.String},System.Int64,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day14_Tests.Test_NanoReactor_Fuel_Produced_By_1_Trillion_Ore(System.Collections.Generic.List{System.String},System.Int64,System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:Tests.Day14_Tests.Test_NanoReactor_Produce_1_Fuel(System.Collections.Generic.List{System.String},System.Int64,System.Int64)")]